import type { DashboardPageCopy } from "@/types/dashboard"

const shared_en: Omit<DashboardPageCopy, "nav" | "sign_out" | "portal_label" | "overview"> = {
  instances: {
    title: "Instances",
    subtitle: "Manage and monitor your virtual servers.",
    status_labels: {
      running: "Running",
      stopped: "Stopped",
      rebooting: "Rebooting",
      provisioning: "Provisioning",
    },
    action_labels: {
      start: "Start",
      stop: "Stop",
      restart: "Restart",
      rebuild: "Rebuild OS",
      destroy: "Destroy",
    },
    specs: "Specs",
    region: "Region",
    ip_address: "IP address",
    monthly: "Monthly",
    created: "Created",
    manage: "Manage",
    back: "Back to instances",
    usage_title: "Resource usage",
    cpu_usage: "CPU",
    bandwidth_usage: "Bandwidth",
    memory_usage: "Memory",
    average: "avg",
    overview_tab: "Overview",
    danger_zone: "Danger zone",
    confirm_action: "Are you sure?",
    action_running: "Working...",
    reverse_dns: "Reverse DNS",
    tabs: {
      overview: "Overview",
      resize: "Resize",
      snapshots: "Snapshots",
      firewall: "Firewall",
      network: "Network",
      console: "Console",
      settings: "Settings",
      backups: "Backups",
    },
  },
  settings: {
    title: "Instance settings",
    subtitle: "Hostname, credentials, rebuild, and destroy.",
    hostname_label: "Hostname",
    hostname_save: "Save hostname",
    hostname_saving: "Saving...",
    hostname_success: "Hostname updated",
    root_password_title: "Root password",
    root_password_desc: "Generate a temporary root password. Shown once.",
    root_password_reset: "Reset root password",
    root_password_resetting: "Resetting...",
    root_password_success: "Temporary password generated",
    temporary_password_label: "Temporary password",
    rebuild_title: "Rebuild OS",
    rebuild_desc: "Wipe the disk and reinstall a fresh operating system.",
    rebuild_os_label: "Operating system",
    rebuild_submit: "Rebuild instance",
    rebuild_submitting: "Rebuilding...",
    rebuild_success: "Instance rebuilt",
    destroy_title: "Destroy instance",
    destroy_desc: "Permanently delete this server and all local data.",
    destroy_submit: "Destroy instance",
    destroy_submitting: "Destroying...",
    destroy_confirm: "Type the hostname to confirm destruction.",
    destroy_success: "Instance destroyed",
  },
  backups: {
    title: "Automated backups",
    subtitle: "Scheduled snapshots with retention control.",
    enabled_label: "Backups enabled",
    frequency_label: "Frequency",
    frequency_daily: "Daily",
    frequency_weekly: "Weekly",
    retention_label: "Retention (days)",
    last_backup: "Last backup",
    next_backup: "Next backup",
    never: "Never",
    save: "Save policy",
    saving: "Saving...",
    success: "Backup policy updated",
  },
  dns: {
    title: "DNS",
    subtitle: "Manage zones and DNS records for your domains.",
    zones_title: "Zones",
    create_zone: "Add zone",
    creating_zone: "Adding...",
    domain_placeholder: "myshop.ir",
    delete_zone: "Delete zone",
    records_title: "Records",
    add_record: "Add record",
    adding_record: "Adding...",
    record_type: "Type",
    record_name: "Name",
    record_value: "Value",
    record_ttl: "TTL",
    record_priority: "Priority",
    empty_zones: "No DNS zones yet.",
    empty_records: "No records in this zone.",
    zone_created: "Zone created",
    zone_deleted: "Zone deleted",
    record_added: "Record added",
    record_updated: "Record updated",
    record_deleted: "Record deleted",
    save_record: "Save",
    delete_record: "Delete",
  },
  resize: {
    title: "Resize plan",
    subtitle: "Upgrade CPU, RAM, or storage. Storage can only increase.",
    cpu_label: "CPU cores",
    ram_label: "RAM (GB)",
    storage_label: "Storage (GB)",
    new_monthly: "New monthly price",
    price_delta: "Price change",
    mode_label: "Apply mode",
    warm_label: "Warm resize",
    warm_desc: "Apply without reboot when possible.",
    cold_label: "Cold resize",
    cold_desc: "Restart required — safest for major changes.",
    apply: "Apply resize",
    applying: "Applying...",
    no_change: "No changes to apply.",
    confirm_note: "Billing updates immediately. Downgrades are not supported.",
    success: "Instance resized successfully",
  },
  snapshots: {
    title: "Snapshots",
    subtitle: "Point-in-time copies for rollback before risky changes.",
    create: "Create snapshot",
    creating: "Creating...",
    label_placeholder: "e.g. pre-migration",
    restore: "Restore",
    restoring: "Restoring...",
    delete: "Delete",
    size: "Size",
    taken: "Taken",
    status_labels: { ready: "Ready", creating: "Creating" },
    empty: "No snapshots yet.",
    confirm_restore: "Restore this snapshot? Current disk state will be replaced.",
    created_success: "Snapshot created",
    restored_success: "Snapshot restored",
    deleted_success: "Snapshot deleted",
  },
  firewall: {
    title: "Firewall",
    subtitle: "Inbound rules only. All outbound traffic is allowed.",
    add_rule: "Add rule",
    adding: "Adding...",
    label: "Label",
    protocol: "Protocol",
    port_range: "Port",
    port_placeholder: "22 or 8000-8010",
    source: "Source CIDR",
    source_placeholder: "0.0.0.0/0",
    delete: "Remove",
    empty: "No firewall rules.",
    inbound: "Inbound",
    added_success: "Rule added",
    deleted_success: "Rule removed",
  },
  network: {
    title: "Network",
    reverse_dns_title: "Reverse DNS (PTR)",
    reverse_dns_desc: "Hostname returned for reverse lookups on this IP.",
    ptr_placeholder: "host.example.com",
    save: "Save PTR",
    saving: "Saving...",
    saved_success: "Reverse DNS updated",
    attached_ips: "Attached floating IPs",
    attached_volumes: "Attached volumes",
    none_attached: "None attached",
    manage_networking: "Manage in Networking",
  },
  console: {
    title: "Web console",
    subtitle: "Browser-based serial console when SSH is unavailable.",
    connect: "Connect",
    connecting: "Connecting...",
    connected: "Connected",
    disconnect: "Disconnect",
    offline_note: "Start the instance to open the console.",
    hint: "Serial console session. Connect via SSH for production access.",
  },
  account: {
    title: "Account",
    subtitle: "Profile, security, keys, and API access.",
    profile_title: "Profile",
    full_name: "Full name",
    email: "Email",
    save: "Save changes",
    saving: "Saving...",
    profile_success: "Profile updated",
    password_title: "Password",
    current_password: "Current password",
    new_password: "New password",
    change_password: "Change password",
    changing: "Updating...",
    password_success: "Password changed",
    password_mismatch: "Current password is incorrect.",
    two_factor_title: "Two-factor authentication",
    two_factor_desc: "Add an extra layer of security to your account.",
    two_factor_on: "Enabled",
    two_factor_off: "Disabled",
    ssh_title: "SSH keys",
    ssh_desc: "Public keys injected at deploy and available for access.",
    ssh_name: "Key name",
    ssh_name_placeholder: "workstation",
    ssh_key_placeholder: "ssh-ed25519 AAAA...",
    ssh_add: "Add key",
    ssh_adding: "Adding...",
    ssh_empty: "No SSH keys stored.",
    ssh_added_success: "SSH key added",
    ssh_deleted_success: "SSH key removed",
    tokens_title: "API tokens",
    tokens_desc: "Scoped tokens for automation and CI/CD.",
    token_name_placeholder: "ci-deploy",
    token_create: "Create token",
    token_creating: "Creating...",
    token_empty: "No API tokens.",
    token_created_success: "Token created — copy it now",
    token_copy_note: "This secret is shown once. Store it securely.",
    token_last_used: "Last used",
    token_never_used: "Never used",
    revoke: "Revoke",
    sessions_title: "Active sessions",
    sessions_desc: "Devices currently signed in to your account.",
    current_session: "Current",
    revoke_session: "Revoke",
    sessions_revoked_success: "Session revoked",
    delete: "Delete",
    confirm: "Confirm",
    notifications_title: "Notification preferences",
    notifications_desc: "Choose which emails and alerts you receive.",
    notify_billing: "Billing emails",
    notify_tickets: "Support ticket updates",
    notify_security: "Security alerts",
    notify_marketing: "Product updates",
    notify_usage: "Usage threshold alerts",
    notifications_save: "Save preferences",
    notifications_saving: "Saving...",
    notifications_success: "Preferences saved",
  },
  activity: {
    title: "Activity log",
    subtitle: "Audit trail of actions on your account and infrastructure.",
    empty: "No activity recorded yet.",
    category_labels: {
      instance: "Instance",
      billing: "Billing",
      security: "Security",
      support: "Support",
      network: "Network",
    },
    all: "All",
  },
  networking: {
    title: "Networking",
    subtitle: "Floating IPs and block storage volumes.",
    floating_ips_title: "Floating IPs",
    volumes_title: "Block volumes",
    create_ip: "Add floating IP",
    creating_ip: "Provisioning...",
    create_volume: "Create volume",
    creating_volume: "Creating...",
    volume_name_placeholder: "data-volume",
    volume_size: "Size (GB)",
    attach: "Attach",
    detach: "Detach",
    delete: "Delete",
    attached_to: "Attached to",
    available: "Available",
    unattached: "Unattached",
    select_instance: "Select instance",
    ips_empty: "No floating IPs.",
    volumes_empty: "No block volumes.",
    ip_created_success: "Floating IP created",
    volume_created_success: "Volume created",
    attached_success: "Attachment updated",
    detached_success: "Detached",
    deleted_success: "Deleted",
  },
  billing: {
    title: "Billing",
    subtitle: "Review transaction history and settle open invoices.",
    invoice: "Invoice",
    amount: "Amount",
    status: "Status",
    due: "Due",
    issued: "Issued",
    pay_now: "Pay now",
    paying: "Processing...",
    status_labels: {
      paid: "Paid",
      pending: "Pending",
      overdue: "Overdue",
    },
    total_due: "Total due",
    paid_note: "Paid",
    empty: "No invoices to show.",
    payment_methods_title: "Payment methods",
    payment_methods_subtitle: "Cards on file for automatic renewals.",
    add_card: "Add payment method",
    adding_card: "Adding...",
    set_default: "Set default",
    default_badge: "Default",
    expires: "Expires",
    delete_method: "Remove",
    no_methods: "No payment methods on file.",
    method_added: "Card added",
    method_deleted: "Card removed",
    method_default_set: "Default payment method updated",
  },
  support: {
    title: "Support",
    subtitle: "Open a ticket and talk directly with our team.",
    new_ticket: "New ticket",
    subject: "Subject",
    subject_placeholder: "Briefly describe the topic",
    message: "Message",
    message_placeholder: "Describe your issue or request...",
    priority: "Priority",
    priority_labels: { low: "Low", normal: "Normal", high: "High" },
    status_labels: { open: "Open", pending: "Pending", closed: "Closed" },
    submit: "Create ticket",
    submitting: "Creating...",
    reply: "Reply",
    reply_placeholder: "Write your reply...",
    send_reply: "Send reply",
    sending: "Sending...",
    back: "Back to tickets",
    empty: "You haven't opened any tickets yet.",
    created_success: "Ticket created",
    reply_success: "Reply sent",
    you: "You",
    support_agent: "ParsCloud Support",
  },
  orders: {
    title: "Orders",
    subtitle: "Track VPS deployment requests and approval status.",
    order_id: "Order",
    plan: "Configuration",
    region: "Region",
    monthly: "Monthly",
    status: "Status",
    created: "Submitted",
    status_labels: {
      pending: "Pending review",
      approved: "Approved",
      rejected: "Rejected",
    },
    empty: "No orders yet. Configure a server from the homepage to get started.",
    view_instance: "View instance",
    provisioning_note: "Your server is being provisioned — it will appear in Instances shortly.",
  },
}

export const dashboardPageCopyByLocale: Record<string, DashboardPageCopy> = {
  en: {
    nav: {
      overview: "Overview",
      instances: "Instances",
      orders: "Orders",
      networking: "Networking",
      dns: "DNS",
      billing: "Billing",
      support: "Support",
      activity: "Activity",
      account: "Account",
    },
    sign_out: "Sign out",
    portal_label: "Dashboard",
    overview: {
      greeting: "Welcome back",
      subtitle: "A clear view of your services, invoices, and tickets.",
      active_instances: "Active instances",
      monthly_spend: "Monthly spend",
      pending_invoices: "Pending invoices",
      open_tickets: "Open tickets",
      recent_instances: "Recent instances",
      pending_invoices_title: "Pending invoices",
      recent_tickets_title: "Recent tickets",
      view_all: "View all",
      empty_instances: "No instances yet.",
      empty_instances_cta: "Configure a server",
      empty_invoices: "No pending invoices.",
      empty_tickets: "No tickets yet.",
    },
    ...shared_en,
  },
  fa: {
    nav: {
      overview: "نمای کلی",
      instances: "سرورها",
      orders: "سفارش‌ها",
      networking: "شبکه",
      dns: "DNS",
      billing: "صورتحساب",
      support: "پشتیبانی",
      activity: "فعالیت‌ها",
      account: "حساب کاربری",
    },
    sign_out: "خروج",
    portal_label: "داشبورد",
    overview: {
      greeting: "خوش آمدید",
      subtitle: "نمای کلی از سرویس‌ها، صورتحساب‌ها و تیکت‌های شما.",
      active_instances: "سرورهای فعال",
      monthly_spend: "هزینه ماهانه",
      pending_invoices: "صورتحساب‌های باز",
      open_tickets: "تیکت‌های باز",
      recent_instances: "سرورهای اخیر",
      pending_invoices_title: "صورتحساب‌های در انتظار",
      recent_tickets_title: "تیکت‌های اخیر",
      view_all: "مشاهده همه",
      empty_instances: "هنوز سروری ندارید.",
      empty_instances_cta: "پیکربندی سرور",
      empty_invoices: "صورتحساب بازی ندارید.",
      empty_tickets: "تیکتی ثبت نشده است.",
    },
    instances: {
      ...shared_en.instances,
      title: "سرورها",
      subtitle: "سرورهای مجازی خود را مدیریت و پایش کنید.",
      status_labels: {
        running: "فعال",
        stopped: "متوقف",
        rebooting: "در حال ری‌استارت",
        provisioning: "در حال آماده‌سازی",
      },
      action_labels: {
        start: "روشن کردن",
        stop: "خاموش کردن",
        restart: "ری‌استارت",
        rebuild: "نصب مجدد سیستم‌عامل",
        destroy: "حذف سرور",
      },
      specs: "مشخصات",
      region: "منطقه",
      ip_address: "آدرس IP",
      monthly: "هزینه ماهانه",
      created: "تاریخ ایجاد",
      manage: "مدیریت",
      back: "بازگشت به سرورها",
      usage_title: "مصرف منابع",
      cpu_usage: "پردازنده",
      bandwidth_usage: "پهنای باند",
      memory_usage: "حافظه",
      average: "میانگین",
      overview_tab: "نمای کلی",
      danger_zone: "عملیات حساس",
      confirm_action: "آیا مطمئن هستید؟",
      action_running: "در حال انجام...",
      reverse_dns: "Reverse DNS",
      tabs: {
        overview: "نمای کلی",
        resize: "تغییر پلن",
        snapshots: "اسنپ‌شات",
        firewall: "فایروال",
        network: "شبکه",
        console: "کنسول",
        settings: "تنظیمات",
        backups: "پشتیبان‌گیری",
      },
    },
    settings: {
      title: "تنظیمات سرور",
      subtitle: "نام میزبان، اعتبارنامه، نصب مجدد و حذف.",
      hostname_label: "نام میزبان",
      hostname_save: "ذخیره نام میزبان",
      hostname_saving: "در حال ذخیره...",
      hostname_success: "نام میزبان به‌روز شد",
      root_password_title: "رمز root",
      root_password_desc: "یک رمز موقت root بسازید. فقط یک‌بار نمایش داده می‌شود.",
      root_password_reset: "بازنشانی رمز root",
      root_password_resetting: "در حال بازنشانی...",
      root_password_success: "رمز موقت ساخته شد",
      temporary_password_label: "رمز موقت",
      rebuild_title: "نصب مجدد سیستم‌عامل",
      rebuild_desc: "دیسک پاک می‌شود و سیستم‌عامل تازه نصب می‌شود.",
      rebuild_os_label: "سیستم‌عامل",
      rebuild_submit: "نصب مجدد",
      rebuild_submitting: "در حال نصب مجدد...",
      rebuild_success: "سرور دوباره نصب شد",
      destroy_title: "حذف سرور",
      destroy_desc: "این سرور و تمام داده‌های محلی برای همیشه حذف می‌شوند.",
      destroy_submit: "حذف سرور",
      destroy_submitting: "در حال حذف...",
      destroy_confirm: "برای تأیید، نام میزبان را تایپ کنید.",
      destroy_success: "سرور حذف شد",
    },
    backups: {
      title: "پشتیبان‌گیری خودکار",
      subtitle: "اسنپ‌شات زمان‌بندی‌شده با کنترل نگهداری.",
      enabled_label: "پشتیبان‌گیری فعال",
      frequency_label: "تناوب",
      frequency_daily: "روزانه",
      frequency_weekly: "هفتگی",
      retention_label: "نگهداری (روز)",
      last_backup: "آخرین پشتیبان",
      next_backup: "پشتیبان بعدی",
      never: "هرگز",
      save: "ذخیره سیاست",
      saving: "در حال ذخیره...",
      success: "سیاست پشتیبان‌گیری به‌روز شد",
    },
    dns: {
      title: "DNS",
      subtitle: "مدیریت zoneها و رکوردهای دامنه.",
      zones_title: "Zoneها",
      create_zone: "افزودن zone",
      creating_zone: "در حال افزودن...",
      domain_placeholder: "myshop.ir",
      delete_zone: "حذف zone",
      records_title: "رکوردها",
      add_record: "افزودن رکورد",
      adding_record: "در حال افزودن...",
      record_type: "نوع",
      record_name: "نام",
      record_value: "مقدار",
      record_ttl: "TTL",
      record_priority: "اولویت",
      empty_zones: "هنوز zoneی ندارید.",
      empty_records: "رکوردی در این zone نیست.",
      zone_created: "Zone ساخته شد",
      zone_deleted: "Zone حذف شد",
      record_added: "رکورد اضافه شد",
      record_updated: "رکورد به‌روز شد",
      record_deleted: "رکورد حذف شد",
      save_record: "ذخیره",
      delete_record: "حذف",
    },
    resize: {
      title: "تغییر پلن",
      subtitle: "CPU، RAM یا ذخیره‌سازی را ارتقا دهید. فقط افزایش storage مجاز است.",
      cpu_label: "هسته CPU",
      ram_label: "RAM (GB)",
      storage_label: "ذخیره‌سازی (GB)",
      new_monthly: "قیمت ماهانه جدید",
      price_delta: "تغییر قیمت",
      mode_label: "نحوه اعمال",
      warm_label: "Warm resize",
      warm_desc: "بدون ری‌استارت در صورت امکان.",
      cold_label: "Cold resize",
      cold_desc: "نیاز به ری‌استارت — برای تغییرات بزرگ‌تر.",
      apply: "اعمال تغییرات",
      applying: "در حال اعمال...",
      no_change: "تغییری برای اعمال نیست.",
      confirm_note: "صورتحساب فوراً به‌روز می‌شود. کاهش منابع پشتیبانی نمی‌شود.",
      success: "پلن با موفقیت به‌روز شد",
    },
    snapshots: {
      title: "اسنپ‌شات‌ها",
      subtitle: "کپی لحظه‌ای برای بازگشت قبل از تغییرات پرریسک.",
      create: "ساخت اسنپ‌شات",
      creating: "در حال ساخت...",
      label_placeholder: "مثلاً pre-migration",
      restore: "بازیابی",
      restoring: "در حال بازیابی...",
      delete: "حذف",
      size: "حجم",
      taken: "زمان",
      status_labels: { ready: "آماده", creating: "در حال ساخت" },
      empty: "هنوز اسنپ‌شاتی ندارید.",
      confirm_restore: "این اسنپ‌شات بازیابی شود؟ وضعیت فعلی دیسک جایگزین می‌شود.",
      created_success: "اسنپ‌شات ساخته شد",
      restored_success: "بازیابی انجام شد",
      deleted_success: "اسنپ‌شات حذف شد",
    },
    firewall: {
      title: "فایروال",
      subtitle: "فقط قوانین ورودی. ترافیک خروجی آزاد است.",
      add_rule: "افزودن قانون",
      adding: "در حال افزودن...",
      label: "برچسب",
      protocol: "پروتکل",
      port_range: "پورت",
      port_placeholder: "22 یا 8000-8010",
      source: "منبع CIDR",
      source_placeholder: "0.0.0.0/0",
      delete: "حذف",
      empty: "قانونی تعریف نشده.",
      inbound: "ورودی",
      added_success: "قانون اضافه شد",
      deleted_success: "قانون حذف شد",
    },
    network: {
      title: "شبکه",
      reverse_dns_title: "Reverse DNS (PTR)",
      reverse_dns_desc: "نام میزبان برای جستجوی معکوس این IP.",
      ptr_placeholder: "host.example.com",
      save: "ذخیره PTR",
      saving: "در حال ذخیره...",
      saved_success: "Reverse DNS به‌روز شد",
      attached_ips: "IPهای شناور متصل",
      attached_volumes: "Volumeهای متصل",
      none_attached: "متصل نیست",
      manage_networking: "مدیریت در بخش شبکه",
    },
    console: {
      title: "کنسول وب",
      subtitle: "دسترسی سریالی از مرورگر وقتی SSH در دسترس نیست.",
      connect: "اتصال",
      connecting: "در حال اتصال...",
      connected: "متصل",
      disconnect: "قطع اتصال",
      offline_note: "برای باز کردن کنسول، سرور را روشن کنید.",
      hint: "جلسه نمایشی — VNC واقعی در حالت دمو فعال نیست.",
    },
    account: {
      title: "حساب کاربری",
      subtitle: "پروفایل، امنیت، کلیدها و دسترسی API.",
      profile_title: "پروفایل",
      full_name: "نام کامل",
      email: "ایمیل",
      save: "ذخیره تغییرات",
      saving: "در حال ذخیره...",
      profile_success: "پروفایل به‌روز شد",
      password_title: "رمز عبور",
      current_password: "رمز فعلی",
      new_password: "رمز جدید",
      change_password: "تغییر رمز",
      changing: "در حال به‌روزرسانی...",
      password_success: "رمز عبور تغییر کرد",
      password_mismatch: "رمز فعلی درست نیست.",
      two_factor_title: "احراز هویت دو مرحله‌ای",
      two_factor_desc: "لایه امنیتی اضافه برای حساب شما.",
      two_factor_on: "فعال",
      two_factor_off: "غیرفعال",
      ssh_title: "کلیدهای SSH",
      ssh_desc: "کلیدهای عمومی برای deploy و دسترسی.",
      ssh_name: "نام کلید",
      ssh_name_placeholder: "workstation",
      ssh_key_placeholder: "ssh-ed25519 AAAA...",
      ssh_add: "افزودن کلید",
      ssh_adding: "در حال افزودن...",
      ssh_empty: "کلید SSH ذخیره نشده.",
      ssh_added_success: "کلید اضافه شد",
      ssh_deleted_success: "کلید حذف شد",
      tokens_title: "توکن‌های API",
      tokens_desc: "توکن‌های محدود برای اتوماسیون.",
      token_name_placeholder: "ci-deploy",
      token_create: "ساخت توکن",
      token_creating: "در حال ساخت...",
      token_empty: "توکن API وجود ندارد.",
      token_created_success: "توکن ساخته شد — همین الان کپی کنید",
      token_copy_note: "این secret فقط یک‌بار نمایش داده می‌شود.",
      token_last_used: "آخرین استفاده",
      token_never_used: "هرگز",
      revoke: "لغو",
      sessions_title: "نشست‌های فعال",
      sessions_desc: "دستگاه‌هایی که وارد حساب شما شده‌اند.",
      current_session: "فعلی",
      revoke_session: "لغو",
      sessions_revoked_success: "نشست لغو شد",
      delete: "حذف",
      confirm: "تأیید",
      notifications_title: "ترجیحات اعلان",
      notifications_desc: "ایمیل‌ها و هشدارهایی که دریافت می‌کنید را انتخاب کنید.",
      notify_billing: "ایمیل‌های صورتحساب",
      notify_tickets: "به‌روزرسانی تیکت پشتیبانی",
      notify_security: "هشدارهای امنیتی",
      notify_marketing: "به‌روزرسانی محصول",
      notify_usage: "هشدار آستانه مصرف",
      notifications_save: "ذخیره ترجیحات",
      notifications_saving: "در حال ذخیره...",
      notifications_success: "ترجیحات ذخیره شد",
    },
    activity: {
      title: "گزارش فعالیت",
      subtitle: "ردپای اقدامات روی حساب و زیرساخت.",
      empty: "فعالیتی ثبت نشده.",
      category_labels: {
        instance: "سرور",
        billing: "صورتحساب",
        security: "امنیت",
        support: "پشتیبانی",
        network: "شبکه",
      },
      all: "همه",
    },
    networking: {
      title: "شبکه",
      subtitle: "IP شناور و volumeهای block storage.",
      floating_ips_title: "IPهای شناور",
      volumes_title: "Block volumeها",
      create_ip: "افزودن IP شناور",
      creating_ip: "در حال ساخت...",
      create_volume: "ساخت volume",
      creating_volume: "در حال ساخت...",
      volume_name_placeholder: "data-volume",
      volume_size: "حجم (GB)",
      attach: "اتصال",
      detach: "جداسازی",
      delete: "حذف",
      attached_to: "متصل به",
      available: "آزاد",
      unattached: "بدون اتصال",
      select_instance: "انتخاب سرور",
      ips_empty: "IP شناوری ندارید.",
      volumes_empty: "volumeی ندارید.",
      ip_created_success: "IP ساخته شد",
      volume_created_success: "Volume ساخته شد",
      attached_success: "اتصال به‌روز شد",
      detached_success: "جداسازی انجام شد",
      deleted_success: "حذف شد",
    },
    billing: {
      title: "صورتحساب",
      subtitle: "تاریخچه تراکنش‌ها را ببینید و صورتحساب‌ها را پرداخت کنید.",
      invoice: "صورتحساب",
      amount: "مبلغ",
      status: "وضعیت",
      due: "مهلت پرداخت",
      issued: "تاریخ صدور",
      pay_now: "پرداخت",
      paying: "در حال پرداخت...",
      status_labels: {
        paid: "پرداخت‌شده",
        pending: "در انتظار",
        overdue: "معوق",
      },
      total_due: "مجموع قابل پرداخت",
      paid_note: "پرداخت‌شده",
      empty: "صورتحسابی وجود ندارد.",
      payment_methods_title: "روش‌های پرداخت",
      payment_methods_subtitle: "کارت‌های ذخیره‌شده برای تمدید خودکار.",
      add_card: "افزودن کارت آزمایشی",
      adding_card: "در حال افزودن...",
      set_default: "پیش‌فرض کردن",
      default_badge: "پیش‌فرض",
      expires: "انقضا",
      delete_method: "حذف",
      no_methods: "روش پرداختی ثبت نشده.",
      method_added: "کارت اضافه شد",
      method_deleted: "کارت حذف شد",
      method_default_set: "روش پرداخت پیش‌فرض به‌روز شد",
    },
    support: {
      title: "پشتیبانی",
      subtitle: "تیکت بسازید و با تیم ما گفت‌وگو کنید.",
      new_ticket: "تیکت جدید",
      subject: "موضوع",
      subject_placeholder: "موضوع را کوتاه بنویسید",
      message: "پیام",
      message_placeholder: "مشکل یا درخواست خود را شرح دهید...",
      priority: "اولویت",
      priority_labels: { low: "کم", normal: "معمولی", high: "زیاد" },
      status_labels: { open: "باز", pending: "در انتظار", closed: "بسته" },
      submit: "ثبت تیکت",
      submitting: "در حال ثبت...",
      reply: "پاسخ",
      reply_placeholder: "پاسخ خود را بنویسید...",
      send_reply: "ارسال پاسخ",
      sending: "در حال ارسال...",
      back: "بازگشت به تیکت‌ها",
      empty: "هنوز تیکتی ثبت نکرده‌اید.",
      created_success: "تیکت با موفقیت ثبت شد",
      reply_success: "پاسخ شما ارسال شد",
      you: "شما",
      support_agent: "پشتیبانی پارس‌کلود",
    },
    orders: {
      title: "سفارش‌ها",
      subtitle: "وضعیت درخواست‌های استقرار VPS را پیگیری کنید.",
      order_id: "سفارش",
      plan: "پیکربندی",
      region: "منطقه",
      monthly: "ماهانه",
      status: "وضعیت",
      created: "تاریخ ثبت",
      status_labels: {
        pending: "در انتظار بررسی",
        approved: "تأیید شده",
        rejected: "رد شده",
      },
      empty: "هنوز سفارشی ندارید. از صفحه اصلی یک سرور پیکربندی کنید.",
      view_instance: "مشاهده سرور",
      provisioning_note: "سرور شما در حال آماده‌سازی است — به‌زودی در بخش سرورها نمایش داده می‌شود.",
    },
  },
}
